### ISSUE TITLE
Migrate to Androidx

### ISSUE THREAD

**Issue by pavelustenko** [voximplant/react-native-foreground-service#12]
Do you plan to migrate your libs to androidx?

**Comment by YuliaGrigorieva** [comment]
Hello @pavelustenko ,

Yes, we plan to update `react-native-foreground-service` module next week.

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
Hello,

We have just released v2.0.0 for RN 0.60 compatibility.

Best regards,
Yulia Grigorieva
