### ISSUE TITLE
Setting  Icon Name

### ISSUE THREAD

**Issue by bennito254** [voximplant/react-native-foreground-service#2]
How is the icon name supposed to be set?

Plus, I also second @agat from #issue 1. A simple screen with Start, Stop buttons will be fine to get everybody started.
Thank you for the library.

**Comment by YuliaGrigorieva** [comment]
Hello!

Icon name should be set to NotificationConfig.icon as string representing icon name.
Icon for the notification should be located in drawable or mipmap resource directory of the android app folder.

We have creates a simple demo project: https://github.com/voximplant/react-native-foreground-service-demo

Demo project contains notification icon (ic_notification.png) in drawable-..dpi folders, for example: https://github.com/voximplant/react-native-foreground-service-demo/tree/master/android/app/src/main/res/drawable-hdpi
Icon name is set the following way: 
```
const notificationConfig = {
    id: 3456,
    title: 'Foreground Service',
    text: 'Foreground service is running',
    icon: 'ic_notification',
    priority: 0
};
```
See full source code [here](https://github.com/voximplant/react-native-foreground-service-demo/blob/39b3ef3c359748c45179d01a16b18cb93ec3ca65/App.js#L35)

Best regards,
Yulia Grigorieva

**Comment by bennito254** [comment]
Thank you sir!

**Comment by roysG** [comment]
Where you add the execute background code?
