### ISSUE TITLE
incorrect import in README

### ISSUE THREAD

**Issue by yaheath** [voximplant/react-native-foreground-service#7]
The README says the import line to add to MainActivity.java should be:
 `import com.voximplant.VIForegroundServicePackage;`
however that doesn't work.

The correct import looks like this:
`import com.voximplant.foregroundservice.VIForegroundServicePackage;`

**Comment by YuliaGrigorieva** [comment]
Hello, @yaheath!

Thank you for reporting the issue!

I have updated the README file.

Best regards,
Yulia Grigorieva
